#!/bin/bash

read -p "Enter url : " url
read -p "Enter playlist items : " items
yt-dlp -f 'bestvideo[height<=1080]+bestaudio/best[height<=1080]' --playlist-items $items -o "%(playlist_index)s-%(title)s.%(ext)s" $url
